# pre-compact-snapshot.ps1
# PreCompact Hook: Auto-save session progress snapshot before context compaction
# Trigger: /compact (manual) or auto-compaction
# Output: docs/tracking/active/session-snapshot.md

$ErrorActionPreference = 'SilentlyContinue'

$projectRoot = $env:CLAUDE_PROJECT_DIR
if (-not $projectRoot) {
    $projectRoot = Split-Path -Parent $PSScriptRoot
}

$snapshotDir = Join-Path $projectRoot 'docs/tracking/active'
$snapshotPath = Join-Path $snapshotDir 'session-snapshot.md'

# Ensure directory exists
if (-not (Test-Path $snapshotDir)) {
    New-Item -ItemType Directory -Path $snapshotDir -Force | Out-Null
}

# Timestamp
$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

# Read sprint-status.yaml to find active stories
$sprintStatusPath = Join-Path $projectRoot 'docs/implementation-artifacts/sprint-status.yaml'
$activeStories = @()
if (Test-Path $sprintStatusPath) {
    $content = Get-Content $sprintStatusPath -Raw -Encoding UTF8
    $regexMatches = [regex]::Matches($content, '(\S+):\s*(in-progress|review)')
    foreach ($m in $regexMatches) {
        $activeStories += $m.Groups[1].Value
    }
}

# List active tracking files
$trackingFiles = @()
$trackingDir = Join-Path $projectRoot 'docs/tracking/active'
if (Test-Path $trackingDir) {
    $trackingFiles = Get-ChildItem -Path $trackingDir -Filter '*.track.md' -Name
}

# Build snapshot content (English for AI consumption / token efficiency)
$lines = @()
$lines += '# Session Progress Snapshot'
$lines += ''
$lines += '> Auto-generated by PreCompact Hook before context compaction.'
$lines += "> Timestamp: $timestamp"
$lines += ''
$lines += '## Active Stories (in-progress / review)'
$lines += ''
if ($activeStories.Count -gt 0) {
    foreach ($s in $activeStories) {
        $lines += "- $s"
    }
} else {
    $lines += '- (none)'
}
$lines += ''
$lines += '## Tracked Files'
$lines += ''
if ($trackingFiles.Count -gt 0) {
    foreach ($f in $trackingFiles) {
        $lines += "- $f"
    }
} else {
    $lines += '- (none)'
}
$lines += ''
$lines += '## Recovery Hint'
$lines += ''
$lines += 'After compaction, read this snapshot to restore working context.'

$snapshot = $lines -join "`n"
[System.IO.File]::WriteAllText($snapshotPath, $snapshot, [System.Text.UTF8Encoding]::new($false))

# Output to stdout (injected as context by Claude Code hook mechanism)
Write-Output "--- PreCompact snapshot saved to $snapshotPath ($timestamp) ---"
$storiesStr = $activeStories -join ', '
Write-Output "Active Stories: $storiesStr"
